-- ========================================
-- CREAR TABLAS EN ORACLE PARA EL PROYECTO
-- Usuario: riffly_m
-- Base de datos: localhost:1521/XE
-- ========================================


-- Crear secuencias para IDs
CREATE SEQUENCE PRODUCTOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CLIENTES_SEQ START WITH 1 INCREMENT BY 1;

-- Tabla PRODUCTOS
CREATE TABLE PRODUCTOS (
    ID NUMBER DEFAULT PRODUCTOS_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    PRECIO NUMBER(10,2) NOT NULL,
    DESCRIPCION CLOB,
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE
);

-- Tabla CLIENTES
CREATE TABLE CLIENTES (
    ID NUMBER DEFAULT CLIENTES_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    TELEFONO VARCHAR2(20),
    DIRECCION VARCHAR2(500),
    FECHA_REGISTRO TIMESTAMP DEFAULT SYSDATE
);

-- Crear índices
CREATE INDEX IDX_PRODUCTOS_NOMBRE ON PRODUCTOS(NOMBRE);
CREATE INDEX IDX_CLIENTES_EMAIL ON CLIENTES(EMAIL);
CREATE INDEX IDX_CLIENTES_NOMBRE ON CLIENTES(NOMBRE);

-- Insertar datos de prueba
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, DESCRIPCION)
VALUES ('Laptop Dell', 1200.50, 'Laptop Dell XPS 15 con procesador i7');

INSERT INTO PRODUCTOS (NOMBRE, PRECIO, DESCRIPCION)
VALUES ('Mouse Logitech', 25.99, 'Mouse inalámbrico Logitech MX Master 3');

INSERT INTO PRODUCTOS (NOMBRE, PRECIO, DESCRIPCION)
VALUES ('Teclado Mecánico', 89.99, 'Teclado mecánico RGB con switches Cherry MX');

INSERT INTO CLIENTES (NOMBRE, EMAIL, TELEFONO, DIRECCION)
VALUES ('Juan Pérez', 'juan.perez@example.com', '555-0101', 'Calle 123, Ciudad');

INSERT INTO CLIENTES (NOMBRE, EMAIL, TELEFONO, DIRECCION)
VALUES ('María García', 'maria.garcia@example.com', '555-0102', 'Avenida 456, Ciudad');

INSERT INTO CLIENTES (NOMBRE, EMAIL, TELEFONO, DIRECCION)
VALUES ('Carlos López', 'carlos.lopez@example.com', '555-0103', 'Boulevard 789, Ciudad');

COMMIT;

-- Verificar las tablas
SELECT 'PRODUCTOS' AS TABLA, COUNT(*) AS CANTIDAD FROM PRODUCTOS
UNION ALL
SELECT 'CLIENTES' AS TABLA, COUNT(*) AS CANTIDAD FROM CLIENTES;

-- Mostrar estructura de las tablas
DESCRIBE PRODUCTOS;
DESCRIBE CLIENTES;

